# Production Profile Configuration
spring:
  # Database Configuration
  # Note: For persistence, replace it with Postgres, MySQL, etc.
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  # H2 Console disabled for production
  h2:
    console:
      enabled: false

  # JPA Configuration (production)
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false

  # Batch Configuration (production)
  batch:
    job:
      enabled: false  # Jobs started via API
    jdbc:
      initialize-schema: always
      platform: h2

# Production-specific logging
logging:
  level:
    org.sitmun.mbtiles: INFO
    org.springframework.batch: INFO
    root: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Production-specific actuator configuration
management:
  endpoint:
    health:
      show-details: never  # Hide detailed health info in production
  endpoints:
    web:
      exposure:
        include: health  # Minimal endpoints for production 